namespace Asn2_GoodSam.Migrations.ClientMigrations
{
    using Asn2_GoodSam.Models.Client;
    using Microsoft.AspNet.Identity;
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;

    internal sealed class Configuration : DbMigrationsConfiguration<Asn2_GoodSam.Models.Client.ClientContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = true;
            MigrationsDirectory = @"Migrations\ClientMigrations";
        }

        protected override void Seed(Asn2_GoodSam.Models.Client.ClientContext context)
        {

            context.Ethnicity.AddOrUpdate(
                new Ethnicity { EthnicityId = 1, EthnicityName = "Declined" },
                new Ethnicity { EthnicityId = 2, EthnicityName = "Caucasian" },
                new Ethnicity { EthnicityId = 3, EthnicityName = "Black" },
                new Ethnicity { EthnicityId = 4, EthnicityName = "Asian" },
                new Ethnicity { EthnicityId = 5, EthnicityName = "Indigenous" },
                new Ethnicity { EthnicityId = 6, EthnicityName = "Latin" },
                new Ethnicity { EthnicityId = 7, EthnicityName = "Middle Eastern" },
                new Ethnicity { EthnicityId = 8, EthnicityName = "Other" },
                new Ethnicity { EthnicityId = 9, EthnicityName = "South Asian" },
                new Ethnicity { EthnicityId = 10, EthnicityName = "South East Asian" }

            );

            context.Age.AddOrUpdate(
                new Age { AgeId = 1, AgeName = "Adult>24<65" },
                new Age { AgeId = 2, AgeName = "Youth>12<19" },
                new Age { AgeId = 3, AgeName = "Youth>18<25" },
                new Age { AgeId = 4, AgeName = "Child<13" },
                new Age { AgeId = 5, AgeName = "Senior>64" }
            );

            context.Gender.AddOrUpdate(
                new Gender { GenderId = 1, GenderName = "M" },
                new Gender { GenderId = 2, GenderName = "F" },
                new Gender { GenderId = 3, GenderName = "T" }
            );

            context.FiscalYear.AddOrUpdate(
                new FiscalYear { FiscalYearId = 1, FiscalYearName = "10-11" },
                new FiscalYear { FiscalYearId = 2, FiscalYearName = "11-12" },
                new FiscalYear { FiscalYearId = 3, FiscalYearName = "12-13" },
                new FiscalYear { FiscalYearId = 4, FiscalYearName = "13-14" },
                new FiscalYear { FiscalYearId = 5, FiscalYearName = "14-15" },
                new FiscalYear { FiscalYearId = 6, FiscalYearName = "15-16" },
                new FiscalYear { FiscalYearId = 7, FiscalYearName = "16-17" }
             );

            context.RiskLevel.AddOrUpdate(
               new RiskLevel { RiskLevelId = 1, RiskLevelName = "High" },
               new RiskLevel { RiskLevelId = 2, RiskLevelName = "DVU" }
       );
            context.Crisis.AddOrUpdate(
               new Crisis { CrisisId = 1, CrisisName = "Call" },
               new Crisis { CrisisId = 2, CrisisName = "Accompaniment" },
               new Crisis { CrisisId = 3, CrisisName = "Drop-in" }
       );

            context.Service.AddOrUpdate(
                new Service { ServiceId = 1, ServiceName = "File" },
                new Service { ServiceId = 2, ServiceName = "N/A" }
        );

            context.Program.AddOrUpdate(
                new Program { ProgramId = 1, ProgramName = "Crisis" },
                new Program { ProgramId = 2, ProgramName = "Court" },
                new Program { ProgramId = 3, ProgramName = "DVU" },
                new Program { ProgramId = 4, ProgramName = "MCFD" },
                new Program { ProgramId = 5, ProgramName = "SMART" }
        );
            context.RiskStatus.AddOrUpdate(
                new RiskStatus { RiskStatusId = 1, RiskStatusName = "Pending" },
                new RiskStatus { RiskStatusId = 2, RiskStatusName = "Complete" }
        );
            context.AssignedWorker.AddOrUpdate(
                new AssignedWorker { AssignedWorkerId = 1, AssignedWorkerName = "None" },
                new AssignedWorker { AssignedWorkerId = 2, AssignedWorkerName = "Michelle" },
                new AssignedWorker { AssignedWorkerId = 3, AssignedWorkerName = "Tyra" },
                new AssignedWorker { AssignedWorkerId = 4, AssignedWorkerName = "Louise" },
                new AssignedWorker { AssignedWorkerId = 5, AssignedWorkerName = "Angela" },
                new AssignedWorker { AssignedWorkerId = 6, AssignedWorkerName = "Dave" },
                new AssignedWorker { AssignedWorkerId = 7, AssignedWorkerName = "Troy" },
                new AssignedWorker { AssignedWorkerId = 8, AssignedWorkerName = "Michael" },
                new AssignedWorker { AssignedWorkerId = 9, AssignedWorkerName = "Manpreet" },
                new AssignedWorker { AssignedWorkerId = 10, AssignedWorkerName = "Patrick" }
        );
            context.ReferralSource.AddOrUpdate(
                new ReferralSource { ReferralSourceId = 1, ReferralSourceName = "Community Agency" },
                new ReferralSource { ReferralSourceId = 2, ReferralSourceName = "Family/Friend" },
                new ReferralSource { ReferralSourceId = 3, ReferralSourceName = "Government" },
                new ReferralSource { ReferralSourceId = 4, ReferralSourceName = "CVAP" },
                new ReferralSource { ReferralSourceId = 5, ReferralSourceName = "CBVS" }
        );

            context.ReferralContact.AddOrUpdate(
                new ReferralContact { ReferralContactId = 1, ReferralContactName = "PBVS" },
                new ReferralContact { ReferralContactId = 2, ReferralContactName = "MCFD" },
                new ReferralContact { ReferralContactId = 3, ReferralContactName = "VictimLINK" },
                new ReferralContact { ReferralContactId = 4, ReferralContactName = "TH" },
                new ReferralContact { ReferralContactId = 5, ReferralContactName = "Self" },
                new ReferralContact { ReferralContactId = 6, ReferralContactName = "FNS" },
                new ReferralContact { ReferralContactId = 7, ReferralContactName = "Medical" },
                new ReferralContact { ReferralContactId = 8, ReferralContactName = "Other" }
        );
            context.Incident.AddOrUpdate(
                new Incident { IncidentId = 1, IncidentName = "Abduction" },
                new Incident { IncidentId = 2, IncidentName = "Adult Historical Sexual Assault" },
                new Incident { IncidentId = 3, IncidentName = "Adult Sexual Assault" },
                new Incident { IncidentId = 4, IncidentName = "Partner Assault" },
                new Incident { IncidentId = 5, IncidentName = "Attempted Murder" },
                new Incident { IncidentId = 6, IncidentName = "Child Physical Assault" },
                new Incident { IncidentId = 7, IncidentName = "Child Sexual Abuse/Exploitation" },
                new Incident { IncidentId = 8, IncidentName = "Criminal Harassment/Stalking" },
                new Incident { IncidentId = 9, IncidentName = "Elder Abuse" },
                new Incident { IncidentId = 10, IncidentName = "Human Trafficking" },
                new Incident { IncidentId = 11, IncidentName = "Murder" },
                new Incident { IncidentId = 12, IncidentName = "N/A" },
                new Incident { IncidentId = 13, IncidentName = "Other" },
                new Incident { IncidentId = 14, IncidentName = "Other Assault" },
                new Incident { IncidentId = 15, IncidentName = "Other Crime - DV" },
                new Incident { IncidentId = 16, IncidentName = "Other Familial Assault" },
                new Incident { IncidentId = 17, IncidentName = "Threatening" },
                new Incident { IncidentId = 18, IncidentName = "Youth Sexual Assault/Exploitation" }
                );

            context.AbuserRelationship.AddOrUpdate(
                new AbuserRelationship { AbuserRelationshipId = 1, AbuserRelationshipName = "Acquaintance" },
                new AbuserRelationship { AbuserRelationshipId = 2, AbuserRelationshipName = "Bad Date" },
                new AbuserRelationship { AbuserRelationshipId = 3, AbuserRelationshipName = "DNA" },
                new AbuserRelationship { AbuserRelationshipId = 4, AbuserRelationshipName = "Ex-Partner" },
                new AbuserRelationship { AbuserRelationshipId = 5, AbuserRelationshipName = "Friend" },
                new AbuserRelationship { AbuserRelationshipId = 6, AbuserRelationshipName = "Multiple Perps" },
                new AbuserRelationship { AbuserRelationshipId = 7, AbuserRelationshipName = "N/A" },
                new AbuserRelationship { AbuserRelationshipId = 8, AbuserRelationshipName = "Other" },
                new AbuserRelationship { AbuserRelationshipId = 9, AbuserRelationshipName = "Other Familial" },
                new AbuserRelationship { AbuserRelationshipId = 10, AbuserRelationshipName = "Parent" },
                new AbuserRelationship { AbuserRelationshipId = 11, AbuserRelationshipName = "Partner" },
                new AbuserRelationship { AbuserRelationshipId = 12, AbuserRelationshipName = "Sibling" },
                new AbuserRelationship { AbuserRelationshipId = 13, AbuserRelationshipName = "Stranger" }
                );

            context.VictimOfIncident.AddOrUpdate(
                new VictimOfIncident { VictimOfIncidentId = 1, VictimOfIncidentName = "Primary" },
                new VictimOfIncident { VictimOfIncidentId = 2, VictimOfIncidentName = "Secondary" }
                );

            context.FamilyViolenceFile.AddOrUpdate(
                new FamilyViolenceFile { FamilyViolenceFileId = 1, FamilyViolenceFileName = "Yes" },
                new FamilyViolenceFile { FamilyViolenceFileId = 2, FamilyViolenceFileName = "No" },
                new FamilyViolenceFile { FamilyViolenceFileId = 3, FamilyViolenceFileName = "N/A" }
                );

            context.RepeatClient.AddOrUpdate(
                new RepeatClient { RepeatClientId = 1, RepeatClientName = null },
                new RepeatClient { RepeatClientId = 2, RepeatClientName = "Yes" }
                );

            context.DuplicateFile.AddOrUpdate(
                new DuplicateFile { DuplicateFileId = 1, DuplicateFileName = null },
                new DuplicateFile { DuplicateFileId = 2, DuplicateFileName = "Yes" }
                );

            context.StatusOfFile.AddOrUpdate(
                new StatusOfFile { StatusOfFileId = 1, StatusOfFileName = "Open" },
                new StatusOfFile { StatusOfFileId = 2, StatusOfFileName = "Reopened" },
                new StatusOfFile { StatusOfFileId = 3, StatusOfFileName = "Closed" },
                new StatusOfFile { StatusOfFileId = 4, StatusOfFileName = "None" }
            );

            context.SexWork.AddOrUpdate(
                new SexWork { SexWorkId = 1, SexWorkName = "Yes" },
                new SexWork { SexWorkId = 2, SexWorkName = "No" },
                new SexWork { SexWorkId = 3, SexWorkName = "N/A" }
            );

            context.MultiplePerpetrators.AddOrUpdate(
                new MultiplePerpetrators { MultiplePerpetratorsId = 1, MultiplePerpetratorsName = "Yes" },
                new MultiplePerpetrators { MultiplePerpetratorsId = 2, MultiplePerpetratorsName = "No" },
                new MultiplePerpetrators { MultiplePerpetratorsId = 3, MultiplePerpetratorsName = "N/A" }
            );

            context.DrugFacilitatedAssault.AddOrUpdate(
                new DrugFacilitatedAssault { DrugFacilitatedAssaultId = 1, DrugFacilitatedAssaultName = "Yes" },
                new DrugFacilitatedAssault { DrugFacilitatedAssaultId = 2, DrugFacilitatedAssaultName = "No" },
                new DrugFacilitatedAssault { DrugFacilitatedAssaultId = 3, DrugFacilitatedAssaultName = "N/A" }
            );

            context.CityOfAssault.AddOrUpdate(
                new CityOfAssault { CityOfAssaultName = "Surrey" },
                new CityOfAssault { CityOfAssaultName = "Abbotsford" },
                new CityOfAssault { CityOfAssaultName = "Agassiz" },
                new CityOfAssault { CityOfAssaultName = "Boston Bar" },
                new CityOfAssault { CityOfAssaultName = "Burnaby" },
                new CityOfAssault { CityOfAssaultName = "Chilliwack" },
                new CityOfAssault { CityOfAssaultName = "Coquitlam" },
                new CityOfAssault { CityOfAssaultName = "Delta" },
                new CityOfAssault { CityOfAssaultName = "Harrison Hot Springs" },
                new CityOfAssault { CityOfAssaultName = "Hope" },
                new CityOfAssault { CityOfAssaultName = "Langley" },
                new CityOfAssault { CityOfAssaultName = "Maple Ridge" },
                new CityOfAssault { CityOfAssaultName = "Mission" },
                new CityOfAssault { CityOfAssaultName = "New Westminister" },
                new CityOfAssault { CityOfAssaultName = "Pitt Meadows" },
                new CityOfAssault { CityOfAssaultName = "Port Coquitlam" },
                new CityOfAssault { CityOfAssaultName = "Port Moody" },
                new CityOfAssault { CityOfAssaultName = "Vancouver" },
                new CityOfAssault { CityOfAssaultName = "White Rock" },
                new CityOfAssault { CityOfAssaultName = "Yale" },
                new CityOfAssault { CityOfAssaultName = "Other-BC" },
                new CityOfAssault { CityOfAssaultName = "Out-of-Province" },
                new CityOfAssault { CityOfAssaultName = "International" }
            );

            context.CityOfResidence.AddOrUpdate(
                new CityOfResidence { CityOfResidenceName = "Surrey" },
                new CityOfResidence { CityOfResidenceName = "Abbotsford" },
                new CityOfResidence { CityOfResidenceName = "Agassiz" },
                new CityOfResidence { CityOfResidenceName = "Boston Bar" },
                new CityOfResidence { CityOfResidenceName = "Burnaby" },
                new CityOfResidence { CityOfResidenceName = "Chilliwack" },
                new CityOfResidence { CityOfResidenceName = "Coquitlam" },
                new CityOfResidence { CityOfResidenceName = "Delta" },
                new CityOfResidence { CityOfResidenceName = "Harrison Hot Springs" },
                new CityOfResidence { CityOfResidenceName = "Hope" },
                new CityOfResidence { CityOfResidenceName = "Langley" },
                new CityOfResidence { CityOfResidenceName = "Maple Ridge" },
                new CityOfResidence { CityOfResidenceName = "Mission" },
                new CityOfResidence { CityOfResidenceName = "New Westminister" },
                new CityOfResidence { CityOfResidenceName = "Pitt Meadows" },
                new CityOfResidence { CityOfResidenceName = "Port Coquitlam" },
                new CityOfResidence { CityOfResidenceName = "Port Moody" },
                new CityOfResidence { CityOfResidenceName = "Vancouver" },
                new CityOfResidence { CityOfResidenceName = "White Rock" },
                new CityOfResidence { CityOfResidenceName = "Yale" },
                new CityOfResidence { CityOfResidenceName = "Other-BC" },
                new CityOfResidence { CityOfResidenceName = "Out-of-Province" },
                new CityOfResidence { CityOfResidenceName = "International" }
            );

            context.ReferringHospital.AddOrUpdate(
                new ReferringHospital { ReferringHospitalName = "Abbotsford Regional Hospital" },
                new ReferringHospital { ReferringHospitalName = "Surrey Memorial Hospital" },
                new ReferringHospital { ReferringHospitalName = "Burnaby Hospital" },
                new ReferringHospital { ReferringHospitalName = "Chilliwack General Hospital" },
                new ReferringHospital { ReferringHospitalName = "Delta Hospital" },
                new ReferringHospital { ReferringHospitalName = "Eagle Ridge Hospital" },
                new ReferringHospital { ReferringHospitalName = "Fraser Canyon Hospital" },
                new ReferringHospital { ReferringHospitalName = "Langley Hospital" },
                new ReferringHospital { ReferringHospitalName = "Mission Hospital" },
                new ReferringHospital { ReferringHospitalName = "Peace Arch Hospital" },
                new ReferringHospital { ReferringHospitalName = "Ridge Meadows Hospital" },
                new ReferringHospital { ReferringHospitalName = "Royal Columbia Hospital" }
            );

            context.HospitalAttended.AddOrUpdate(
                new HospitalAttended { HospitalAttendedName = "Abbotsford Regional Hospital" },
                new HospitalAttended { HospitalAttendedName = "Surrey Memorial Hospital" },
                new HospitalAttended { HospitalAttendedName = "Burnaby Hospital" },
                new HospitalAttended { HospitalAttendedName = "Chilliwack General Hospital" },
                new HospitalAttended { HospitalAttendedName = "Delta Hospital" },
                new HospitalAttended { HospitalAttendedName = "Eagle Ridge Hospital" },
                new HospitalAttended { HospitalAttendedName = "Fraser Canyon Hospital" },
                new HospitalAttended { HospitalAttendedName = "Langley Hospital" },
                new HospitalAttended { HospitalAttendedName = "Mission Hospital" },
                new HospitalAttended { HospitalAttendedName = "Peace Arch Hospital" },
                new HospitalAttended { HospitalAttendedName = "Ridge Meadows Hospital" },
                new HospitalAttended { HospitalAttendedName = "Royal Columbia Hospital" }
            );

            context.SocialWorkAttendance.AddOrUpdate(
                new SocialWorkAttendance { SocialWorkAttendanceName = "Yes" },
                new SocialWorkAttendance { SocialWorkAttendanceName = "No" },
                new SocialWorkAttendance { SocialWorkAttendanceName = "N/A" }
            );

            context.PoliceAttendance.AddOrUpdate(
                new PoliceAttendance { PoliceAttendanceName = "Yes" },
                new PoliceAttendance { PoliceAttendanceName = "No" },
                new PoliceAttendance { PoliceAttendanceName = "N/A" }
            );

            context.VictimServicesAttendance.AddOrUpdate(
                new VictimServicesAttendance { VictimServicesAttendanceName = "Yes" },
                new VictimServicesAttendance { VictimServicesAttendanceName = "No" },
                new VictimServicesAttendance { VictimServicesAttendanceName = "N/A" }
            );

            context.MedicalOnly.AddOrUpdate(
                new MedicalOnly { MedicalOnlyName = "Yes" },
                new MedicalOnly { MedicalOnlyName = "No" },
                new MedicalOnly { MedicalOnlyName = "N/A" }
            );

            context.EvidenceStored.AddOrUpdate(
                new EvidenceStored { EvidenceStoredName = "Yes" },
                new EvidenceStored { EvidenceStoredName = "No" },
                new EvidenceStored { EvidenceStoredName = "N/A" }
            );

            context.HIVMeds.AddOrUpdate(
                new HIVMeds { HIVMedsName = "Yes" },
                new HIVMeds { HIVMedsName = "No" },
                new HIVMeds { HIVMedsName = "N/A" }
            );


            context.ReferredToCBVS.AddOrUpdate(
                new ReferredToCBVS { ReferredToCBVSName = "Yes" },
                new ReferredToCBVS { ReferredToCBVSName = "No" },
                new ReferredToCBVS { ReferredToCBVSName = "PVBS Only" },
                new ReferredToCBVS { ReferredToCBVSName = "N/A" }
            );


            context.PoliceReported.AddOrUpdate(
                new PoliceReported { PoliceReportedName = "Yes" },
                new PoliceReported { PoliceReportedName = "No" },
                new PoliceReported { PoliceReportedName = "N/A" }
            );

            context.ThirdPartyReport.AddOrUpdate(
                new ThirdPartyReport { ThirdPartyReportName = "Yes" },
                new ThirdPartyReport { ThirdPartyReportName = "No" },
                new ThirdPartyReport { ThirdPartyReportName = "N/A" }
            );

            context.BadDateReport.AddOrUpdate(
                new BadDateReport { BadDateReportName = "Yes" },
                new BadDateReport { BadDateReportName = "No" },
                new BadDateReport { BadDateReportName = "N/A" }
            );

            context.Clients.AddOrUpdate(
                    new Client
                    {
                        ClientId = 1,
                        Surname = "Shmoe",
                        FirstName = "Joe",
                        ChildrenZeroToSix = 1,
                        ChildrenSevenToTwelve = 2,
                        ChildrenThirteenToEighteen = 3,
                        Month = 1,
                        Day = 1,
                        PoliceFileNumber = "11-11111",
                        CourtFileNumber = 1,
                        SWCFileNumber = 1,
                        RiskAssessmentAssignedTo = "Assessor",
                        AbuserName = "Jensen,Adam",
                        EthnicityId = 2,
                        GenderId = 1,
                        AgeId = 2,
                        FiscalYearId = 2,
                        CrisisId = 2,
                        ServiceId = 2,
                        ProgramId = 1,
                        AssignedWorkerId = 1,
                        StatusOfFileId = 1,
                        ReferralSourceId = 1,
                        ReferralContactId = 1,
                        IncidentId = 2,
                        AbuserRelationshipId = 1,
                        VictimOfIncidentId = 1,
                        DuplicateFileId = 1,
                        FamilyViolenceFileId = 1,
                        RiskLevelId = 1,
                        RepeatClientId = 1
                    },

                    new Client
                    {
                        ClientId = 2,
                        Surname = "Smores",
                        FirstName = "Jake",
                        ChildrenZeroToSix = 1,
                        ChildrenSevenToTwelve = 2,
                        ChildrenThirteenToEighteen = 3,
                        Month = 1,
                        Day = 1,
                        PoliceFileNumber = "11-11111",
                        CourtFileNumber = 1,
                        SWCFileNumber = 1,
                        RiskAssessmentAssignedTo = "Assessor",
                        AbuserName = "Jensen,Adam",
                        EthnicityId = 2,
                        GenderId = 1,
                        AgeId = 2,
                        FiscalYearId = 2,
                        CrisisId = 2,
                        ServiceId = 1,
                        ProgramId = 1,
                        AssignedWorkerId = 1,
                        StatusOfFileId = 1,
                        ReferralSourceId = 1,
                        ReferralContactId = 1,
                        IncidentId = 2,
                        AbuserRelationshipId = 1,
                        VictimOfIncidentId = 1,
                        DuplicateFileId = 1,
                        FamilyViolenceFileId = 1,
                        RiskLevelId = 1,
                        RepeatClientId = 1
                    },

                    new Client
                    {
                        ClientId = 3,
                        Surname = "Jensen",
                        FirstName = "Adam",
                        ChildrenZeroToSix = 1,
                        ChildrenSevenToTwelve = 2,
                        ChildrenThirteenToEighteen = 3,
                        Month = 1,
                        Day = 1,
                        PoliceFileNumber = "11-11111",
                        CourtFileNumber = 1,
                        SWCFileNumber = 1,
                        RiskAssessmentAssignedTo = "Assessor",
                        AbuserName = "Jensen,Adam",
                        EthnicityId = 2,
                        GenderId = 1,
                        AgeId = 2,
                        FiscalYearId = 2,
                        CrisisId = 2,
                        ServiceId = 2,
                        ProgramId = 1,
                        AssignedWorkerId = 1,
                        StatusOfFileId = 1,
                        ReferralSourceId = 1,
                        ReferralContactId = 1,
                        IncidentId = 2,
                        AbuserRelationshipId = 1,
                        VictimOfIncidentId = 1,
                        DuplicateFileId = 1,
                        FamilyViolenceFileId = 1,
                        RiskLevelId = 1,
                        RepeatClientId = 1
                    },

                    new Client
                    {
                        ClientId = 4,
                        Surname = "Striper",
                        FirstName = "Candy",
                        ChildrenZeroToSix = 1,
                        ChildrenSevenToTwelve = 2,
                        ChildrenThirteenToEighteen = 3,
                        Month = 1,
                        Day = 1,
                        PoliceFileNumber = "11-11111",
                        CourtFileNumber = 1,
                        SWCFileNumber = 1,
                        RiskAssessmentAssignedTo = "Assessor",
                        AbuserName = "Jensen,Adam",
                        EthnicityId = 2,
                        GenderId = 1,
                        AgeId = 2,
                        FiscalYearId = 2,
                        CrisisId = 2,
                        ServiceId = 1,
                        ProgramId = 1,
                        AssignedWorkerId = 3,
                        StatusOfFileId = 2,
                        ReferralSourceId = 1,
                        ReferralContactId = 1,
                        IncidentId = 2,
                        AbuserRelationshipId = 1,
                        VictimOfIncidentId = 1,
                        DuplicateFileId = 1,
                        FamilyViolenceFileId = 1,
                        RiskLevelId = 1,
                        RepeatClientId = 1
                    },

                    new Client
                    {
                        ClientId = 5,
                        Surname = "Jacket",
                        FirstName = "Leather",
                        ChildrenZeroToSix = 1,
                        ChildrenSevenToTwelve = 2,
                        ChildrenThirteenToEighteen = 3,
                        Month = 1,
                        Day = 1,
                        PoliceFileNumber = "11-11111",
                        CourtFileNumber = 1,
                        SWCFileNumber = 1,
                        RiskAssessmentAssignedTo = "Assessor",
                        AbuserName = "Jensen,Adam",
                        EthnicityId = 2,
                        GenderId = 1,
                        AgeId = 2,
                        FiscalYearId = 2,
                        CrisisId = 2,
                        ServiceId = 2,
                        ProgramId = 1,
                        AssignedWorkerId = 4,
                        StatusOfFileId = 2,
                        ReferralSourceId = 1,
                        ReferralContactId = 1,
                        IncidentId = 2,
                        AbuserRelationshipId = 1,
                        VictimOfIncidentId = 1,
                        DuplicateFileId = 1,
                        FamilyViolenceFileId = 1,
                        RiskLevelId = 1,
                        RepeatClientId = 1
                    },

                    new Client
                    {
                        ClientId = 6,
                        Surname = "House",
                        FirstName = "Gregory",
                        ChildrenZeroToSix = 1,
                        ChildrenSevenToTwelve = 2,
                        ChildrenThirteenToEighteen = 3,
                        Month = 1,
                        Day = 1,
                        PoliceFileNumber = "11-11111",
                        CourtFileNumber = 1,
                        SWCFileNumber = 1,
                        RiskAssessmentAssignedTo = "Assessor",
                        AbuserName = "Jensen,Adam",
                        EthnicityId = 2,
                        GenderId = 1,
                        AgeId = 2,
                        FiscalYearId = 2,
                        CrisisId = 2,
                        ServiceId = 1,
                        ProgramId = 1,
                        AssignedWorkerId = 2,
                        StatusOfFileId = 3,
                        ReferralSourceId = 1,
                        ReferralContactId = 1,
                        IncidentId = 2,
                        AbuserRelationshipId = 1,
                        VictimOfIncidentId = 1,
                        DuplicateFileId = 1,
                        FamilyViolenceFileId = 1,
                        RiskLevelId = 1,
                        RepeatClientId = 1
                    },

                    new Client
                    {
                        ClientId = 7,
                        Surname = "Skywalker",
                        FirstName = "Luke",
                        ChildrenZeroToSix = 1,
                        ChildrenSevenToTwelve = 2,
                        ChildrenThirteenToEighteen = 3,
                        Month = 1,
                        Day = 1,
                        PoliceFileNumber = "11-11111",
                        CourtFileNumber = 1,
                        SWCFileNumber = 1,
                        RiskAssessmentAssignedTo = "Assessor",
                        AbuserName = "Jensen,Adam",
                        EthnicityId = 2,
                        GenderId = 1,
                        AgeId = 2,
                        FiscalYearId = 2,
                        CrisisId = 2,
                        ServiceId = 2,
                        ProgramId = 1,
                        AssignedWorkerId = 3,
                        StatusOfFileId = 2,
                        ReferralSourceId = 1,
                        ReferralContactId = 1,
                        IncidentId = 2,
                        AbuserRelationshipId = 1,
                        VictimOfIncidentId = 1,
                        DuplicateFileId = 1,
                        FamilyViolenceFileId = 1,
                        RiskLevelId = 1,
                        RepeatClientId = 1
                    },

                    new Client
                    {
                        ClientId = 8,
                        Surname = "Underwood",
                        FirstName = "Francis",
                        ChildrenZeroToSix = 1,
                        ChildrenSevenToTwelve = 2,
                        ChildrenThirteenToEighteen = 3,
                        Month = 1,
                        Day = 1,
                        PoliceFileNumber = "11-11111",
                        CourtFileNumber = 1,
                        SWCFileNumber = 1,
                        RiskAssessmentAssignedTo = "Assessor",
                        AbuserName = "Jensen,Adam",
                        EthnicityId = 2,
                        GenderId = 1,
                        AgeId = 2,
                        FiscalYearId = 2,
                        CrisisId = 2,
                        ServiceId = 1,
                        ProgramId = 5,
                        AssignedWorkerId = 1,
                        StatusOfFileId = 3,
                        ReferralSourceId = 1,
                        ReferralContactId = 1,
                        IncidentId = 2,
                        AbuserRelationshipId = 1,
                        VictimOfIncidentId = 1,
                        DuplicateFileId = 1,
                        FamilyViolenceFileId = 1,
                        RiskLevelId = 1,
                        RepeatClientId = 1
                    },
                     new Client
                     {
                         ClientId = 9,
                         Surname = "Goodman",
                         FirstName = "Saul",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 2,
                         ProgramId = 5,
                         AssignedWorkerId = 1,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1
                     },
                     new Client
                     {
                         ClientId = 10,
                         Surname = "White",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 1,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 11,
                         Surname = "Pinkman",
                         FirstName = "Jesse",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 2,
                         ProgramId = 1,
                         AssignedWorkerId = 1,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1
                     },
                      new Client
                     {
                         ClientId = 12,
                         Surname = "Yellow",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 1,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 13,
                         Surname = "Black",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 1,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 14,
                         Surname = "Grey",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 1,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 15,
                         Surname = "Whazx",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 2,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 16,
                         Surname = "Whiteeeeeeee",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 2,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 17,
                         Surname = "Purpley",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 2,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 18,
                         Surname = "Green",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 3,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 19,
                         Surname = "Red",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 3,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 20,
                         Surname = "Orange",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 3,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 21,
                         Surname = "Maroon",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 4,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 22,
                         Surname = "Magenta",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 4,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 23,
                         Surname = "Kid",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 4,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 24,
                         Surname = "Lame",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 5,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 25,
                         Surname = "Kangaroo",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 5,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 26,
                         Surname = "Crazy",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 5,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 27,
                         Surname = "Loopy",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 6,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 28,
                         Surname = "Train",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 6,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 29,
                         Surname = "Waaaaat",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 6,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                      new Client
                     {
                         ClientId = 30,
                         Surname = "Thirty",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 7,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 31,
                         Surname = "Thirty-two",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 7,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 32,
                         Surname = "Jones",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 7,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 33,
                         Surname = "Krock",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 8,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 34,
                         Surname = "Mineral",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 8,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 35,
                         Surname = "Marie",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 8,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 36,
                         Surname = "Rock",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 9,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 37,
                         Surname = "Manson",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 9,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 38,
                         Surname = "Language",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 9,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 39,
                         Surname = "Breaking",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 10,
                         StatusOfFileId = 3,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 40,
                         Surname = "Bad",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 10,
                         StatusOfFileId = 2,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     },
                     new Client
                     {
                         ClientId = 41,
                         Surname = "Good",
                         FirstName = "Walter",
                         ChildrenZeroToSix = 1,
                         ChildrenSevenToTwelve = 2,
                         ChildrenThirteenToEighteen = 3,
                         Month = 1,
                         Day = 1,
                         PoliceFileNumber = "11-11111",
                         CourtFileNumber = 1,
                         SWCFileNumber = 1,
                         RiskAssessmentAssignedTo = "Assessor",
                         AbuserName = "Jensen,Adam",
                         EthnicityId = 2,
                         GenderId = 1,
                         AgeId = 2,
                         FiscalYearId = 2,
                         CrisisId = 2,
                         ServiceId = 1,
                         ProgramId = 1,
                         AssignedWorkerId = 10,
                         StatusOfFileId = 1,
                         ReferralSourceId = 1,
                         ReferralContactId = 1,
                         IncidentId = 2,
                         AbuserRelationshipId = 1,
                         VictimOfIncidentId = 1,
                         DuplicateFileId = 1,
                         FamilyViolenceFileId = 1,
                         RiskLevelId = 1,
                         RepeatClientId = 1

                     }


                );



        }
    }
}

