// <auto-generated />
namespace Asn2_GoodSam.Migrations.UserMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class UserCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201503050119187_UserCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
